removing debugging in config-pin, removing sudo because we don't have it

diff --git a/board/nerves-common/rootfs-additions/bin/config-pin b/board/nerves-common/rootfs-additions/bin/config-pin
--- a/board/nerves-common/rootfs-additions/bin/config-pin
+++ b/board/nerves-common/rootfs-additions/bin/config-pin
@@ -1,8 +1,5 @@
 #!/bin/ash
 
-set -e
-set -v
-
 # Some important directories for use later
 OCPDIR=/sys/devices/ocp.*
 GPIODIR=/sys/class/gpio
@@ -1017,7 +1014,7 @@ config_pin () {
 			eval GPIO="\$${PIN}_GPIO"
 			FILE="$GPIODIR/gpio$GPIO/direction"
 			if [ -e $FILE ] ; then
-				sudo -A bash -c "echo $DIR > $FILE" || (echo_err "Cannot write gpio direction file: $FILE" && exit 1)
+				echo $DIR > $FILE || (echo_err "Cannot write gpio direction file: $FILE" && exit 1)
 			else
 				echo_err "WARNING: GPIO pin not exported, cannot set direction or value!"
 			fi
@@ -1027,13 +1024,13 @@ config_pin () {
 			# Expand filename using shell globbing
 			for FILE in $OCPDIR${PIN}_pinmux/state ; do
 				echo_dbg "echo $MODE > $FILE"
-				sudo -A bash -c "echo $MODE > $FILE" || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				echo $MODE > $FILE || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
 			done
 		else
 			# Expand filename using shell globbing
 			for FILE in $OCPDIR/${PIN}_pinmux.*/state ; do
 				echo_dbg "echo $MODE > $FILE"
-				sudo -A bash -c "echo $MODE > $FILE" || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				echo $MODE > $FILE || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
 			done
 		fi
 	fi
