adding device tree overlays and extra busybox config

diff --git a/board/nerves-common/rootfs-additions/bin/config-pin b/board/nerves-common/rootfs-additions/bin/config-pin
--- a/board/nerves-common/rootfs-additions/bin/config-pin
+++ b/board/nerves-common/rootfs-additions/bin/config-pin
@@ -879,7 +879,7 @@ load_cape () {
 			# Expand filename using shell globbing
 			for FILE in $SLOTS ; do
 				echo_std Loading $DTBO overlay
-				sudo -A bash -c "echo $DTBO > $SLOTS" || (echo_err "Error loading device tree overlay file: $DTBO" && exit 1)
+				ash -c "echo $DTBO > $SLOTS" || (echo_err "Error loading device tree overlay file: $DTBO" && exit 1)
 				sleep 1
 			done
 		fi
